# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2af80584fbf1222fd83afb82f21f967e01759678a1b0afa64ad52e6d1e951e11deb655d2d5b6246327515cb6f08a346da88cdf538318dc29ffab2a27289a0395

test:
  secret_key_base: 7e271ef0041f73b15f68dfac1ac66d9f186087e0d8723734b7eaba0d7682bc55349fc01598c3abb1497d08f9ad6e688bd68e66c516f0428792bc77794942481b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
